/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: (typeof import('./../components/HelloWorld.vue'))['default'];
    'IconBi:5Square': (typeof import('~icons/bi/5-square'))['default'];
    IconLocalNoIcon: (typeof import('~icons/local/no-icon'))['default'];
    'IconMdi:emoticon': (typeof import('~icons/mdi/emoticon'))['default'];
    IconMdiEmoticon: (typeof import('~icons/mdi/emoticon'))['default'];
    NButton: (typeof import('naive-ui'))['NButton'];
    NCard: (typeof import('naive-ui'))['NCard'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    SvgIcon: (typeof import('./../components/custom/svg-icon.vue'))['default'];
  }
}
